version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  one:
    executor: node/default
    steps:
      - run: sleep 5  && echo 1
  two:
    executor: node/default
    steps:
      - run: sleep 5  && echo 2
  three:
    executor: node/default
    steps:
      - run: sleep 5  && echo 3
  four:
    executor: node/default
    steps:
      - run: sleep 5  && echo 4
  five:
    executor: node/default
    steps:
      - run: sleep 5  && echo 5
workflows:
  build:
    jobs:
      - one
      - two
      - three
      - four
      - five
  matrix-tests:
    jobs:
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 14.4.0
                - 12.18.1
                - 10.21.0
