version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    executor: node/default
    parallelism: 1
    steps:
      - run: ./run-busy
workflows:
  matrix-tests:
    jobs:
      - build:
          context: Test
      # - node/test:
      #     pkg-manager: yarn
      #     matrix:
      #       parameters:
      #         version:
      #           - 14.4.0
      #           - 12.18.1
      #           - 10.21.0
