version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  build:
    executor: node/default
    steps:
      - run: sleep 5  && echo 1
        parallel: true
      - run: sleep 5  && echo 2
        parallel: true
      - run: sleep 5  && echo 3
        parallel: true
      - run: sleep 5  && echo 4
        parallel: true
      - run: sleep 5  && echo 5
        parallel: true
workflows:
  matrix-tests:
    jobs:
      - build:
          context: Test
      - node/test:
          pkg-manager: yarn
          matrix:
            parameters:
              version:
                - 14.4.0
                - 12.18.1
                - 10.21.0
